services:
  storage:
    image: ton-storage:2025.02
    restart: on-failure
    volumes:
      - ./storage-db:/storage-db
    ports:
      - 3333:3333/udp
    command: ./storage-daemon -d -v 4 -p 5555 -C global.config.json -D /storage-db -I 82.148.29.191:3333

  client:
    image: ton-storage:2025.02
    tty: true
    profiles:
      - no-start
    volumes:
      - ./storage-db:/storage-db
    command: ./storage-daemon-cli -I storage:5555 -k /storage-db/cli-keys/client -p /storage-db/cli-keys/server.pub
